ALTER TABLE `gm_tickets` 
ADD COLUMN `map` INT NOT NULL DEFAULT '0' AFTER `createtime`,
ADD COLUMN `posX` FLOAT NOT NULL DEFAULT '0' AFTER `map`,
ADD COLUMN `posY` FLOAT NOT NULL DEFAULT '0' AFTER `posX`,
ADD COLUMN `posZ` FLOAT NOT NULL DEFAULT '0' AFTER `posY`;