UPDATE trinity_string SET content_default = "The %s field of %s was set to %u" WHERE entry= '299';

DELETE FROM `command` WHERE `name` = "modify arena";
DELETE FROM `command` WHERE `name` = 'modify arena'; 
DELETE FROM `command` WHERE `name` = 'flusharenapoints'; 
DELETE FROM `command` WHERE `name` = 'debug arena'; 

REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor add','2','Syntax: .honor add $amount\r\n\r\nAdd a certain amount of honor (gained in lifetime) to the selected player.');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor addkill','2','Syntax: .honor addkikll\r\n\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor update','2','Syntax: .honor update\r\n\r\nForce honor to be update');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('honor show','1','Syntax: .honor show\r\n\r\nDisplay the honor stats of the selected player');
REPLACE INTO `command` (`name`, `security`, `help`) VALUES('modify honor','2','Syntax: .modify honor $field $value\r\n\r\nAdd $value to an honor $field (it\'s just for debug , values won\'t be saved at player logout)\r\nField list: points / rank / todaykills / yesterdaykills / yesterdayhonor /\r\nthisweekkills / thisweekhonor / lastweekkills / lastweekhonor /\r\nlastweekstanding / lifetimedishonorablekills / lifetimehonorablekills ');

INSERT INTO trinity_string (entry,content_default) VALUES (345,"Private ");
INSERT INTO trinity_string (entry,content_default) VALUES (346,"Corporal ");
INSERT INTO trinity_string (entry,content_default) VALUES (347,"Sergeant ");
INSERT INTO trinity_string (entry,content_default) VALUES (348,"Master Sergeant ");
INSERT INTO trinity_string (entry,content_default) VALUES (349,"Sergeant Major ");
INSERT INTO trinity_string (entry,content_default) VALUES (350,"Knight ");
INSERT INTO trinity_string (entry,content_default) VALUES (351,"Knight-Lieutenant ");
INSERT INTO trinity_string (entry,content_default) VALUES (352,"Knight-Captain ");
INSERT INTO trinity_string (entry,content_default) VALUES (353,"Knight-Champion ");
INSERT INTO trinity_string (entry,content_default) VALUES (354,"Lieutenant Commander ");
INSERT INTO trinity_string (entry,content_default) VALUES (355,"Commander ");
INSERT INTO trinity_string (entry,content_default) VALUES (356,"Marshal ");
INSERT INTO trinity_string (entry,content_default) VALUES (357,"Field Marshal ");
INSERT INTO trinity_string (entry,content_default) VALUES (358,"Grand Marshal ");
INSERT INTO trinity_string (entry,content_default) VALUES (359,"Scout ");
INSERT INTO trinity_string (entry,content_default) VALUES (360,"Grunt ");
INSERT INTO trinity_string (entry,content_default) VALUES (361,"Sergeant ");
INSERT INTO trinity_string (entry,content_default) VALUES (362,"Senior Sergeant ");
INSERT INTO trinity_string (entry,content_default) VALUES (363,"First Sergeant ");
INSERT INTO trinity_string (entry,content_default) VALUES (364,"Stone Guard ");
INSERT INTO trinity_string (entry,content_default) VALUES (365,"Blood Guard ");
INSERT INTO trinity_string (entry,content_default) VALUES (366,"Legionnare ");
INSERT INTO trinity_string (entry,content_default) VALUES (367,"Centurion ");
INSERT INTO trinity_string (entry,content_default) VALUES (368,"Champion ");
INSERT INTO trinity_string (entry,content_default) VALUES (369,"Lieutenant General ");
INSERT INTO trinity_string (entry,content_default) VALUES (370,"General ");
INSERT INTO trinity_string (entry,content_default) VALUES (371,"Warlord ");
INSERT INTO trinity_string (entry,content_default) VALUES (372,"High Warlord ");
INSERT INTO trinity_string (entry,content_default) VALUES (373,"Game Master ");
INSERT INTO trinity_string (entry,content_default) VALUES (374,"No Rank ");
INSERT INTO trinity_string (entry,content_default) VALUES (375,"%s (Rank %u)");
INSERT INTO trinity_string (entry,content_default) VALUES (376,"Today: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r]");
INSERT INTO trinity_string (entry,content_default) VALUES (377,"Yesterday: [Kills: |c0000ff00%u|r] [Honor: %u]");
INSERT INTO trinity_string (entry,content_default) VALUES (378,"This Week: [Kills: |c0000ff00%u|r] [Honor: %u]");
INSERT INTO trinity_string (entry,content_default) VALUES (379,"Last Week: [Kills: |c0000ff00%u|r] [Honor: %u] [Standing: %u]");
INSERT INTO trinity_string (entry,content_default) VALUES (380,"Life Time: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r] [Highest Rank %u: %s]");