#! /bin/bash
NEO_DIR='/opt/neo/';
RETVAL=0;
 
start(){
	screen -AmdS neo_restarter ${NEO_DIR}restarter
}
stop(){
	screen -dr neo_restarter -X "quit"
}
 
start-realm(){
	screen -AmdS neo_realm ${NEO_DIR}bin/neo-realm -c ${NEO_DIR}etc/neorealm.conf
}
stop-realm(){
	screen -dr neo_realm -X "quit"
}
 
start-core(){
    cd ${NEO_DIR}
	screen -AmdS neo_core ${NEO_DIR}bin/neo-core -c ${NEO_DIR}etc/neocore.conf
}
stop-core(){
	screen -dr neo_core -X "quit"
}
 
case $1 in
start)
	start;
	date;
	echo "Restarter started";
;;
stop)
	stop;
	stop-realm;
	stop-core;
	date;
	echo "Restarter stopped";
;;
restart)
	stop;
	start;
	stop-realm;
	stop-core;
	start-realm;
	start-core;
	start;
	date;
	echo "Restarter restarted";
;;
start-realm)
	start-realm;
	date;
	echo "Realm started";
;;
stop-realm)
	stop-realm;
	date;
	echo "Realm stopped";
;;
restart-realm)
	stop-realm;
	start-realm;
	date;
	echo "Realm restarted";
;;
start-core)
	start-core;
	date;
	echo "Core started";
;;
stop-core)
	stop-core;
	date;
	echo "Core stopped";
;;
restart-core)
	stop-core;
	start-core;
	date;
	echo "Core restarted";
;;
start-restarter)
	start;
	date;
	echo "Restarter Démarre";
;;
stop-restarter)
	stop;
	date;
	echo "Restarter stopped";
;;
restart-restarter)
	stop;
	start;
	date;
	echo "Restarter restarted";
;;
status)
	screen -ls
;;
restarter)
	screen -r neo_restarter
;;
realm)
	screen -r neo_realm
;;
core)
	screen -r neo_core
;;
*)
	echo "Usage: $0 {start|stop|restart|start-realm|stop-realm|restart-realm|start-core|stop-core|restart-core|start-restarter|stop-restarter|restart-restarter|status|restarter|realm|core}"
	RETVAL=1
esac
exit $RETVAL;
