#! /bin/bash
while true
do
  PID1=$(pidof neo-core)
  if (( PID1 < 1 ))
  then
        /etc/init.d/neo start-core
  fi
 
  PID2=$(pidof neo-realm)
  if (( PID2 < 1 ))
  then
        /etc/init.d/neo start-realm
  fi
 
  sleep 10
done
